# Generated by Django 5.1 on 2024-08-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='focus_post_updated_4df267_idx',
        ),
    ]
